### ISSUE TITLE
Add option to execute commands before launching a game, and upon closing of a game

### ISSUE THREAD

**Issue by lukeman3000** [theMK2k/MetropolisLauncher#12]
D-Fend Reloaded allows the user to execute commands before the game launches and after the game is closed. This can be useful for opening/closing a midi synth (such as Falcosoft Midi Player, for example), so that the synth only runs while the game is being played.

In the example image below, I have told DFR to execute mt32.exe when the game is launched and to execute kill.exe when the game is closed (although the suffixes are not necessary). These exe files are autohotkey scripts which launch Falcosoft Midi Player and then close it (upon termination of the game), respectively.

When executing a command before the main program, DFR allows the user to "wait before execution of the main program" so that DFR will hold off on launching the game until the command is fully executed. This is a useful feature to ensure that a midi synth is fully initialized before a game launches, although it could be further improved by allowing the user to specify an additional delay (in milliseconds) if more delay is needed.

Observe the other options that DFR allows the user (such as running the commands minimized and in order). This would be a helpful addition to MK2k.

![catsimt](https://user-images.githubusercontent.com/31397270/29758008-b6916838-8b75-11e7-97d8-5f706e34760f.png)

**Comment by theMK2k** [comment]
Understood. Do you happen to know what "not working if using data files as commands" means? What are data files in this case?

**Comment by theMK2k** [comment]
Pre-Launch and Post-Launch commands are now supported.

Please download https://www.metropolis-launcher.net/beta-releases/metropolis_launcher_1.2.0b3-mk2k.zip and test. The feature is available in the Emulator Settings (https://documentation.metropolis-launcher.net/emulator_settings.htm) as a new tab called "Pre- and Post-Launch Commands".

**Comment by BoneofMalkav** [comment]
Tried the Daggerfall paramiters in both Pre and Post Launch Commands
sections, no change.

**Comment by theMK2k** [comment]
Hi @BoneofMalkav, thanks for stepping in. Please provide more details.

What do you mean by "no change"?
What exactly did you put into the Pre- and Post-Launch Commands? (Screenshots of the Launch Command Editor could be helpful)?
