### ISSUE TITLE
Add option for Metropolis Launcher to remember size and position of window so that it opens in the same configuration each time

### ISSUE THREAD

**Issue by lukeman3000** [theMK2k/MetropolisLauncher#13]
**1. Allow MK2k to remember size and position of window so that it opens in the same configuration**

This is a somewhat minor aesthetic feature that I would like to see. D-Fend Reloaded allows the user to choose different options for the interface itself, such as restoring the window size/position from the previous session. Personally, I like starting the frontend in a smaller window. It would be nice if MK2k would remember the sizing and positioning of the window (as well as the various borders of the different sections within the GUI) if desired. An option to reset these to default would also be nice.

Additionally, an option to center the window (in relationship to the overall screen) would be nice.

Example from D-Fend Reloaded:

![7sjmf57](https://user-images.githubusercontent.com/31397270/29758174-01fc8b4e-8b77-11e7-8395-2e33b0e1d003.png)

**Comment by theMK2k** [comment]
The "various borders and sections within" should already be saved and restored.

Metropolis Launcher is currently configured to run maximized by default. Even if we get rid of that and make this optional, I wouldn't opt for save/restore of the window position because this could fail miserably for example if you save a position during a multi monitor setup and restore it at a single monitor setup.

**Comment by theMK2k** [comment]
With low prio, I'll see what I can do about maximized/normal window state (via option) and save/restore of window location.

**Comment by lukeman3000** [comment]
Perhaps at the least, being able to start the launcher in windowed mode and with the size of the window remembered (not necessarily the location) would be nice. Personally, I have autohotkey scripts which start all of my game windows in the center of my screen; I game on a 2560x1440 monitor and much prefer windowed mode for older games due to the fidelity of the graphics.

That said, if window position was remembered (a la D-Fend Reloaded), couldn't the program detect if the window was off-screen, outside of view of the primary monitor, and relocate it accordingly?

**Comment by theMK2k** [comment]
The following beta release
- saves the main window state, size and location on close
- loads and restores main window state, size and location on startup

Currently there is no check for out-of-bounds during restore.

Please download and test. Backup your current Metropolis Launcher installation before extract/overwrite.

https://metropolis-launcher.net/beta-releases/metropolis_launcher_1.2.0b4-mk2k.zip

**Comment by theMK2k** [comment]
done. it is included in the 1.2.0 release
