### ISSUE TITLE
Add right-click context menu option to edit game's options as it relates to emulator settings

### ISSUE THREAD

**Issue by lukeman3000** [theMK2k/MetropolisLauncher#16]
One particular feature of D-Fend Reloaded that I like is that when you right-click a game and click "edit", you can change the emulator settings for that particular game.

In MK2k, it looks like the only way to have discrete emulator settings from game to game (which is very important), is to create individual emulator templates for each game (in a separate menu), and to then select the matching template for the game. It would be handy to be able to perhaps automatically create a template via the right-click context menu, or to somehow make it such that emulator settings for a specific game could be altered by right-clicking the game.

**Comment by theMK2k** [comment]
When right-clicking a **PC - DOS** game in Metropolis Launcher and choosing **Edit Game**, you should see the **DOSBox Config** tab. In this tab you can adjust individual settings just for that game. The template you chose contains the basic settings which all can be overriden. Any overriden setting will be displayed in **bold**.

If you mean other Emulators besides DOSBox, please let me know.
