### ISSUE TITLE
Decrease loading time when entering "Games and Emulation" menu

### ISSUE THREAD

**Issue by lukeman3000** [theMK2k/MetropolisLauncher#17]
I just timed this with my phone, and it took just over 8 seconds to access the "Games and Emulation" menu. This seems a bit long. What is the cause of such a long loading time? I've noticed that subsequent loading times are much shorter, but if the program is closed and re-opened, the initial loading time is very long.

**Comment by theMK2k** [comment]
Metropolis Launcher isn't light weight and hasn't been advertized as such.

The initial loading times are caused by:
- big UI libraries with nice features
- meta data from the database
