### ISSUE TITLE
Errors that occur when adding an installed game directory

### ISSUE THREAD

**Issue by lukeman3000** [theMK2k/MetropolisLauncher#21]
[Video](https://www.youtube.com/watch?v=MAfZG4naefA&feature=youtu.be)

Error messages:

`No tags have been found, the window will be closed`
I don't think this one is an error, but I am curious as to the nature of tags and how/where they might exist as well as their function.

`There has been an error while rescanning a DOSBox game. The error was: Syntax error: Missing operand after 's' operator.`

`Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately`.

`Syntax error: missing operand after 's' operator.`

Details: [https://pastebin.com/hcYCqLUE](https://pastebin.com/hcYCqLUE)

**Comment by theMK2k** [comment]
### Tags

In the emulation scene, filenames are not only carrying the game's name but also meta data in tags:

Example: King's Quest II- Romancing the Throne v2.1 (1987)(Sierra On-Line, Inc.)

Here we have the Version "v2.1", year "(1987)", and Publisher "(Sierra On-Line, Inc.)" as tags.

Now, when you add a game to Metropolis Launcher, it tries to identify tags within the file- and directory names and shows the Tag Parser Settings dialog (the window popping up with the message).

further informations:

https://www.tosecdev.org/tosec-naming-convention
https://documentation.metropolis-launcher.net/tag_parser_settings.htm?zoom_highlightsub=tags

### The Syntax Error

This is a bug, I'll have a look.

**Comment by lukeman3000** [comment]
So, if a game doesn't have any tags that MK2k can find, I can still manually pick the game out of the ROM manager list and auto-populate all data fields in the same way, right?

**Comment by theMK2k** [comment]
If a game file- or directory name doesn't have tags, the Tag Parser Settings window is not neccessary, hence the message. The same meta data can be applied later in the "Edit Game" dialog.

**Comment by theMK2k** [comment]
Could you please provide the list of filenames under your "KQ1 SCI" directory?

I assume one of the executables may have an apastrophe in it's file name. This could be an .exe but also .bat and .com are treated as executables.

I tested with 17.356 DOS releases and never stumbled upon an executable with such a name, though.

**Comment by theMK2k** [comment]
OK, the error is correctly handled now. However, any DOS executable should be DOS-compatible, i.e. follows the 8.3 filename convention.

**Comment by theMK2k** [comment]
Closing this issue now, you'll get a beta build where you can test and verify later.
