### ISSUE TITLE
Request: Command Line Paramaters for DOS games (Probably some Windows games too.)

### ISSUE THREAD

**Issue by BoneofMalkav** [theMK2k/MetropolisLauncher#28]
I noticed that there's nothing for adding additional command line paramters for DOS and Windows games (example. Loading Elder Scrolls II: Daggerfall using FALL.EXE Z.CFG) Was wondering if you could add a text field for that in the Edit Game window.

**Comment by theMK2k** [comment]
Thanks for your suggestions, will look into it!

For the Windows games: You can always create a link file (.lnk) and launch that instead of the game's .exe. In the link properties you can define command line parameters.

**Comment by theMK2k** [comment]
For DOS: a workaround could be that you create a .bat file which launches the game's .exe incl. command line parameters.

**Comment by theMK2k** [comment]
I decided that this requirement will not be realized in the launcher.
For DOS: create a .bat file and use this as the MAIN executable
For WIN: create a .lnk file and use this as the game's executable
