### ISSUE TITLE
Any way to Assist?

### ISSUE THREAD

**Issue by Rendarius** [theMK2k/MetropolisLauncher#29]
Anyway I could help you with this process perhaps??... Maybe by manually collecting the CHD numbers and compiling a list of them?..

EDIT - Sry Im new to Github and tried responding directly to Issue of CHD files...  I SEE I DIDNT scroll down far enough to CLEARLY see the comment area...And I also cant seem to find a way to Delete this comment....  Yeeeeeah a new thing to be a fresh newbie at... Ill learn the web page fast as I always learn fast....

Ok I see I can NOT delete this as I thought might be the csae...  Once again sry.. Please close this and Delete... Ill comment where it belongs.

**Comment by Rendarius** [comment]
[](url)

**Comment by theMK2k** [comment]
all good, welcome aboard :)
