### ISSUE TITLE
Can't download pictures in Moby extras manager

### ISSUE THREAD

**Issue by aaronjsolomon** [theMK2k/MetropolisLauncher#31]
First of all, let me say that I just found this program and it is INSANE. I've been looking for this for a couple years now. I don't see a huge community, but I hope you feel appreciated for this truly amazing piece of software!

An issue I'm having, is that pictures do not download from Moby. Everything behaves as normal--the Extras Manager loads, the list of items shows up on the left, but the picture area is blank, and clicking items on the left does not force a download. (The "Download extras when selected" check box is checked.)

If I hover the mouse over the picture area, I get the popup "tooltip" "Click to Edit / Click here to edit the image", but clicking does nothing but make the popup go away.

Any ideas? Am I missing something? Do I need to create a Moby account? Do I need to update some DLLs?

Thanks much, Aaron

**Comment by theMK2k** [comment]
Hi @aaronjsolomon,

it's nice to hear from people who find Metropolis Launcher useful :)

Mobygames.com currently seems to have a problem with scraping bots which slow the site down to the point of the site being not reachable by users. They are using a service called CloudFlare which stops bots from accessing the site.

You can see this when opening mobygames.com in your browser: a message "Checking your browser before accessing mobygames.com" appears.

When Metropolis Launcher wants to access mobygames.com for the images it will be stopped by said service.

I hope that this is just a temporary measure and will be shut off in the near future.

MobyGames forum entry regarding the same issue: http://www.mobygames.com/forums/dga,2/dgb,2/dgm,241345/#241345

cheers

-- MK2k

**Comment by theMK2k** [comment]
...but I got an idea, stay tuned :)

**Comment by theMK2k** [comment]
It seems, mobygames.com have shut off the bot blocking feature.

The idea I had is that I first check if archive.org's wayback machine has the image and downloads it from there. If not, mobygames.com will be checked next.

Now that mobygames.com currently allows bot access again, I won't rush that feature.

**Comment by aaronjsolomon** [comment]
Very cool!

Is there any way I can help with this project?

I’m a weak coder (barely a scripter), but I am expert in databases (including SQLite), data scrubbing (e.g. with Excel), requirements analysis and documentation, good technical researcher,  well-versed in the software development lifecycle (in a corporate environment, not so much collaboration over github—but I can learn it quickly), and highly knowledgeable of emulation and the ROM scene(s). I can read and edit code and do light code tasks. Very familiar with Windows internals, including a fair amount of API knowledge. Can use Visual Studio. Etc.

I’ve been OCD obsessing over building a completionist ROM collection for a couple years now, even learning how to write Launchbox plugins, but none of the existing tools are powerful enough. Finding Metropolis Launcher was like a godsend—it’s exactly what I would’ve written if I had your coding chops.

Is there anything I can do to help? I’d be happy to e.g. prep data sets for platforms that you haven’t added yet. Sorting and tagging files like music or ROMs is my most zen activity. For example, if you tell me what needs to be done to add another platform (e.g. Sharp X68000), I’d be happy to.

I’d also be down to create some YouTube tutorials or similar content.

Not looking for dev mentorship or experience per se. I’m already well along in my career and busy with a full time job. Definitely not looking to waste your time. But if there’s anything my skill set can do to help the project along, please let me know, because I’m eager to assist.

Also I realize that the issue tracker isn’t the best way to communicate. Feel free to indicate your preferred method of contact, or email me at aaronjsolomon@gmail.com.

Cheers! Aaron

**Comment by theMK2k** [comment]
Thanks for your reply, I'll write you a follow-up email :)

I'll keep this ticket open until next release, where archive.org is properly included in the image retrieval process :)

**Comment by theMK2k** [comment]
done. it is included in 1.2.0 release
