### ISSUE TITLE
Request: Export to LaunchBox

### ISSUE THREAD

**Issue by aaronjsolomon** [theMK2k/MetropolisLauncher#33]
LaunchBox (http://www.launchbox-app.com) is a popular front end that has lots of polished HTPC-style features (e.g., choosing a game from an Apple iTunes-style animated full screen menu system using an Xbox 360 controller), but is severely limited in its data management features compared to Metropolis Launcher.

A very nice workflow would be:

1) Use Metropolis Launcher for intensive data management (including ROM launching) of my entire ROM collection. You might call this "power user mode".

2) Export a subset of those ROMs into LaunchBox, so that e.g. family members could use the HTPC features to browse a subset of ROMs, with hacks etc. filtered out. You might call this "end user mode".

LaunchBox has an plugin framework for extending its functionality using .NET, including modifying its game database (which is actually stored in XML and not a relational database like SQLite).

I envision an export function in Metropolis Launcher that rebuilds LaunchBox's internal XML database on demand, either via the API, or by XML construction.

I realize this is a major request, with many requirements as yet undefined. That said, I'm happy to assist in this effort. I have a deep familiarity with the idiosyncrasies of LaunchBox's data model.

**Comment by theMK2k** [comment]
I assume you're talking about Launchbox's BigBox mode.

I don't actively support paid-for software. So maybe you could have a look yourself? You can harvest the data from the ml.db SQLite file and create the LB's XML file from it?

**Comment by theMK2k** [comment]
On the other hand... if there actually was a nice, free (preferably open source) HTPC style frontend, where an export from Metropolis Launcher would make sense, then we would be talking!

If not, oh well, I'd write my own :)

**Comment by aaronjsolomon** [comment]
Fair enough! :) Getting my ROM data whipped into shape with ML will help immensely, if I attempt such an integration component for BigBox.

I think Kodi is open source and has some HTPC ROM launcher add-in, and I’ll keep an eye out for other options as well. Until further review, I withdraw my request. :)

**Comment by theMK2k** [comment]
Kodi is a good example! I think they'll integrate a HTPC Emulation launcher without the need for a plugin in the next major release, so I'd wait until that happened and jump on their train then :)

From analysis of Kodi's Media databases, the database schema is a bit odd though :)
