### ISSUE TITLE
MobyGames link detection ineffective for MAME ROMs

### ISSUE THREAD

**Issue by aaronjsolomon** [theMK2k/MetropolisLauncher#34]
How can I efficiently link MAME games to their Moby data?

- I added MAME ROMs to ML using the special MAME settings widget, where you specify the MAME exe and related data files, then click the "Scan" button to read games into ML.

- After performing this step, MAME games appear in ML's "Games & Emulation" screen, with the "Game", "Year", and "Developer" columns populated, but all other left blank. Game names are the "friendly name", e.g. "Ninja Baseball Bat Man (World)", and not the "ROM name", e.g. "nbbatman".

- I opened the ROM Browser, which listed all of my imported MAME ROMs, but only displays the MAME filename and inner file in the left panel, both of which are the "unfriendly" ROM name (e.g. "nbbatman"), and not the "friendly" name (e.g. "Ninja Baseball Bat Man (World)").

Moby releases appear on the right side of the ROM Browser, as expected.

At this point, I can select any/all of my MAME ROMs, right-click, and select "Detect MobyGames Links". However, since the basis of comparison is the ROM name and not the friendly game name, the matching algorithm predictably fails to find hardly any matches. It is effectively trying to match "nbbatman" to "Ninja Baseball Bat Man", and that obviously won't work, except in a handful of cases of games with a short, single word name. In my case, matches were found for 337 out of 13364 games. For the remainder of imported MAME ROMs, the match guesses were completely off.

Is there a way to use the MAME friendly game name, and not the ROM file name, as a basis for comparison during MobyGames link detection? The friendly game name is already available and showing in the "Games & Emulations" view, it's just not available in the ROM Browser, where link detection is actually performed. If the friendly name were the basis of comparison during link detection, it would work as well as any other platform.

Or, am I missing something obvious? Although I've read the help file, I'm not 100% confident that I'm approaching MAME game data handling correctly.

Please advise.

**Comment by theMK2k** [comment]
I can't recommend using mobygames meta data with arcade games yet because the quality of it is questionable. A much better meta data source are:

- history.dat
- mameinfo.dat
- gameinit.dat
- Category Files (nplayers.ini and catlist.ini)

That's why you don't see any game being automatically linked to mobygames meta data in the ROM Manager.

I'll have a look into the link detection for the MAME Arcade platform and get back to you.

**Comment by aaronjsolomon** [comment]
I haven’t actually used these supplementary dat files with MAME before, and am not familiar with them. I’ll spend some more time getting familiar with their benefits. I love that ML guides the user into leveraging these various DAT file formats. There’s obviously a ton of great work in the MAME scene compiling data in interesting ways, but it’s usually far from obvious how to incorporate that into your actual setup.

 

As I see it, here are the benefits of allowing users to link MAME games to Moby (assuming I’m not missing something obvious):

*	Consistency of naming conventions, especially game names and company names, like developers and publishers. For example, if the game developer Cave is known as “Cave” in the DAT files, but “CAVE Co., Ltd.” in MobyGames, then updating from MobyGames should keep all the data consistent, so I can e.g. now look at one developer in ML (“CAVE Co., Ltd.”) and see all the games developed by that studio. Otherwise, I presume I’d end up with two developer entries for the same company (which bothers me, though maybe it’s just me).
*	Linkage of arcade games to MobyGames groups. For example, there is an arcade game called “Deathsmiles” that is in the MobyGames group called “Genre: Scrolling shoot ‘em up”, along with tons of other console and arcade shoot ‘em ups. I presume that linking to MobyGames would be necessary for ML to display this group and its constituent games, and have all references to those games be linked to launchable ROMs.
*	Downloading of extras like screenshots.

 

My holy grail system has the following features:

1.	An easy way to see lists of related games (by series, developer, franchise, whatever), with all platforms represented and with all entries launchable. Basically, a way to imaginatively explore video game history, including franchises and companies, by pivoting through complete and consistent data sets.
2.	At least one decent image for each game, either box art or a title screen, to provide visual interest while browsing.
3.	Minimal quasi-duplicative game entries, where two games are really just versions of a single game. For instance, I’d like HD remasters to appear as sub-releases of the original game, and not a whole different game. I’d ESPECIALLY like to consolidate releases into a single game where one game has been given different names in different regions. For example, the game “1943” is varying called (depending on region and platform) “1943: The Battle of Midway”, “1943: The Battle of Valhalla”, “1943: Midway Kaisen”, etc. I’m trying to figure out a way to leverage the data so these all reliably end up under a single game listing, or at least a consistent, single game name, because they are in fact the same game, and the naming variants are only marketing anomalies.

 

#2 seems especially well-served by the MobyGames notion of “groups”.

 

Please keep me posted on your decision whether to incorporate friendly game names for MAME ROMs into the comparison logic for MobyGames link detection.

 

On the other hand, if it’s just a matter of swapping out a couple of object attributes in the source code that feeds the ROM Browser, I might be able to make the code change myself. If you’d think it’s that simple of a fix, and you’d like to encourage contributor edits to source, let me know and I’ll spend some time getting Visual Studio fired up, learning github procedures, etc.

 

Thanks!

**Comment by theMK2k** [comment]
I'll keep you posted about the Moby Link Detection for MAME Arcade. As soon as it is done, you'll get an intermediate build to test :)

**Comment by aaronjsolomon** [comment]
AWESOME

**Comment by theMK2k** [comment]
Done.

When the MAME Arcade platform is chosen, ROM Manager's Moby Link Detection functionality now takes the "Name" field for matching instead of "File", "InnerFile" or "Directory". This should easily match approx. 4000 titles with 100% accuracy.

To test this, you can use the following beta build:

https://metropolis-launcher.net/beta-releases/metropolis_launcher_1.2.0b1-mk2k.zip

Please back up your previous installation before overwriting any data.

**Comment by aaronjsolomon** [comment]
Ace!!

**Comment by theMK2k** [comment]
After testing, please post your results. So we can close the issue or do further work on it :)

**Comment by aaronjsolomon** [comment]
Question:

 

Do you prefer that issues in your issue tracker be treated as highly targeted for quick resolution, or more as a topic around which you’d like all related discussions to occur?

 

I have some closely related follow-up questions having to do with tweaking the UI and data handling. Would you like me to post them to the existing issue, or close the existing one and begin new issues?

**Comment by theMK2k** [comment]
I would suggest you report regarding the issue at hand and open a new one :)
