### ISSUE TITLE
Crash when enabling auto filter row in ROM Browser

### ISSUE THREAD

**Issue by aaronjsolomon** [theMK2k/MetropolisLauncher#35]
Steps to reproduce:
- Open ML and go to Games & Emulation.
- Load the MAME Arcade platform (not sure that matters).
- Right-click a game and open the ROM Browser.
- In a column header of the LEFT table containing the list of user games (with column names "Filename", "Inner File", etc.), right-click and select "Show Auto Filter Row".

At this point, ML displays an unhandled exception dialog
- Title bar text: "Rom Manager"
- Unhandled exception text: "Object variable or With block variable not set."
- Details pasted below.
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object variable or With block variable not set.
   at Microsoft.VisualBasic.CompilerServices.Symbols.Container..ctor(Object Instance)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.LateGet(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack)
   at Metropolis_Launcher.frm_Rom_Manager.gv_Emu_Games_RowCellStyle(Object sender, RowCellStyleEventArgs e)
   at DevExpress.XtraGrid.Views.Grid.GridView.RaiseGetRowCellStyle(Int32 rowHandle, GridColumn column, GridRowCellState state, AppearanceObject appearance)
   at DevExpress.XtraGrid.Views.Grid.GridView.GetRowCellStyle(Int32 rowHandle, GridColumn column, GridRowCellState state, AppearanceObject appearance)
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.UpdateCellAppearanceCore(GridCellInfo cell)
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.UpdateCellAppearance(GridCellInfo cell, Boolean always)
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.CreateCellEditViewInfo(GridCellInfo cell, Boolean calc, Boolean allowCache)
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.RequestCellEditViewInfo(GridCellInfo cell)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawRegularRowCell(GridViewDrawArgs e, GridCellInfo ci)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawRegularRow(GridViewDrawArgs e, GridDataRowInfo ri)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawRow(GridViewDrawArgs e, GridRowInfo ri)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawRows(GridViewDrawArgs e)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawContents(GridViewDrawArgs e)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.Draw(ViewDrawArgs ee)
   at DevExpress.XtraGrid.Views.Base.BaseView.Draw(GraphicsCache e)
   at DevExpress.XtraGrid.GridControl.OnPaint(PaintEventArgs e)
   at DevExpress.Utils.Drawing.ControlPaintHelper.PaintWithErrorHandling(PaintEventArgs paintEventArgs, Int32 layer)
   at DevExpress.Utils.Drawing.ControlPaintHelper.ProcessWMPaint(Message& m)
   at DevExpress.XtraGrid.GridControl.CheckProcessMsg(Message& m)
   at DevExpress.XtraGrid.GridControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Metropolis_Launcher
    Assembly Version: 1.1.1.0
    Win32 Version: 1.1.1.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/Metropolis_Launcher.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
MKNetDXLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/MKNetDXLib.DLL
----------------------------------------
DevExpress.Utils.v15.2
    Assembly Version: 15.2.11.0
    Win32 Version: 15.2.11.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/DevExpress.Utils.v15.2.DLL
----------------------------------------
DevExpress.Data.v15.2
    Assembly Version: 15.2.11.0
    Win32 Version: 15.2.11.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/DevExpress.Data.v15.2.DLL
----------------------------------------
DevExpress.XtraBars.v15.2
    Assembly Version: 15.2.11.0
    Win32 Version: 15.2.11.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/DevExpress.XtraBars.v15.2.DLL
----------------------------------------
AlphaFS
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/AlphaFS.DLL
----------------------------------------
MKNetLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/MKNetLib.DLL
----------------------------------------
DevExpress.BonusSkins.v15.2
    Assembly Version: 15.2.11.0
    Win32 Version: 15.2.11.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/DevExpress.BonusSkins.v15.2.DLL
----------------------------------------
DevExpress.XtraGrid.v15.2
    Assembly Version: 15.2.11.0
    Win32 Version: 15.2.11.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/DevExpress.XtraGrid.v15.2.DLL
----------------------------------------
DevExpress.XtraEditors.v15.2
    Assembly Version: 15.2.11.0
    Win32 Version: 15.2.11.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/DevExpress.XtraEditors.v15.2.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Data.DataSetExtensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.DataSetExtensions/v4.0_4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
DevExpress.Images.v15.2
    Assembly Version: 15.2.11.0
    Win32 Version: 15.2.11.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/DevExpress.Images.v15.2.DLL
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.66.0
    Win32 Version: 1.0.66.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/System.Data.SQLite.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
DevExpress.Printing.v15.2.Core
    Assembly Version: 15.2.11.0
    Win32 Version: 15.2.11.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/DevExpress.Printing.v15.2.Core.DLL
----------------------------------------
DevExpress.XtraRichEdit.v15.2
    Assembly Version: 15.2.11.0
    Win32 Version: 15.2.11.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/DevExpress.XtraRichEdit.v15.2.DLL
----------------------------------------
DevExpress.RichEdit.v15.2.Core
    Assembly Version: 15.2.11.0
    Win32 Version: 15.2.11.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/DevExpress.RichEdit.v15.2.Core.DLL
----------------------------------------
DevExpress.XtraGauges.v15.2.Win
    Assembly Version: 15.2.11.0
    Win32 Version: 15.2.11.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/DevExpress.XtraGauges.v15.2.Win.DLL
----------------------------------------
DevExpress.XtraGauges.v15.2.Core
    Assembly Version: 15.2.11.0
    Win32 Version: 15.2.11.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/DevExpress.XtraGauges.v15.2.Core.DLL
----------------------------------------
DevExpress.XtraPivotGrid.v15.2
    Assembly Version: 15.2.11.0
    Win32 Version: 15.2.11.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/DevExpress.XtraPivotGrid.v15.2.DLL
----------------------------------------
DevExpress.PivotGrid.v15.2.Core
    Assembly Version: 15.2.11.0
    Win32 Version: 15.2.11.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/DevExpress.PivotGrid.v15.2.Core.DLL
----------------------------------------
DevExpress.Office.v15.2.Core
    Assembly Version: 15.2.11.0
    Win32 Version: 15.2.11.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/DevExpress.Office.v15.2.Core.DLL
----------------------------------------
DevExpress.XtraTreeList.v15.2
    Assembly Version: 15.2.11.0
    Win32 Version: 15.2.11.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/DevExpress.XtraTreeList.v15.2.DLL
----------------------------------------
SgmlReaderDll
    Assembly Version: 1.8.7.40394
    Win32 Version: 1.8.7.*
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/SgmlReaderDll.DLL
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
UIAutomationClient
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationClient/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationClient.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Data.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Linq.dll
----------------------------------------
DevExpress.Data.v15.2.Dynamic_bf648e5d-d9df-4699-9bd6-4b2811303041
    Assembly Version: 0.0.0.0
    Win32 Version: 15.2.11.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/DevExpress.Data.v15.2.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
DevExpress.XtraLayout.v15.2
    Assembly Version: 15.2.11.0
    Win32 Version: 15.2.11.0
    CodeBase: file:///F:/LaunchBox/Emulators/Metropolis%20Launcher/dll/DevExpress.XtraLayout.v15.2.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by theMK2k** [comment]
I can reproduce, it isn't dependant on which platform has been chosen.

note to myself: check any grid that implements a RowCellStyle event - there are definitely more than just the one in the ROM Manager.

**Comment by theMK2k** [comment]
Fixed.

To test this, you can use the following beta build:

https://metropolis-launcher.net/beta-releases/metropolis_launcher_1.2.0b1-mk2k.zip

Please back up your previous installation before overwriting any data.

**Comment by aaronjsolomon** [comment]
YES!! That worked!

 

I have some follow-up questions that I’ll write up when I get the chance.

 

Thanks!
