### ISSUE TITLE
Please add "Game" as a selectable column to the left panel of the ROM Browser

### ISSUE THREAD

**Issue by aaronjsolomon** [theMK2k/MetropolisLauncher#36]
Please make the "Game" column from the "Games & Emulation" screen available for selection in the left panel of the ROM Manager.

Manually linking an individual MAME rom to its corresponding Moby game is theoretically possible in the Rom Manager, but it's impractical because only the filename is available to the user in this screen. For non-MAME roms, the filename itself tells the user which game the rom is for, but this is not the case for MAME roms.

Thanks!

**Comment by aaronjsolomon** [comment]
Closing this issue, at least for now. I have lots of picky requirements about data, and I'm going to experiment with meeting some of these requirements running updates directly against the SQLite database. This will help me get more familiar with the application's internals, and it will also stop me from generating tons of potentially low-value or arbitrary change requests.

After spending some time experimenting with the data directly, I'll have a better sense of which changes might be general improvements (vs. my own arbitrary preferences), and can submit issues then.

**Comment by aaronjsolomon** [comment]
Re-opening. I'm still working with the database, but have reflected upon this further. Since you now allow bulk linking of MAME roms to Moby (and it's AWESOME that you do), than it only makes sense to allow selective linking of individual MAME roms as well, and this requires a "Game" column with a friendly name in left panel of the Rom Browser (as described in the original ticket), because there's usually no way for the user to identify a game from its MAME filename alone.

**Comment by theMK2k** [comment]
I added a "Game Name" field to the Rom Manager which in case of the current MAME import functionality will provide the user-friendly name of the game.

For any other platform the field will be in most cases empty, as the game's name will be derived from the MobyGames game name or from the filename itself.

Please test with the following build: https://metropolis-launcher.net/beta-releases/metropolis_launcher_1.2.0b2-mk2k.zip

This build is an incremental update and must be extracted on top of https://metropolis-launcher.net/beta-releases/metropolis_launcher_1.2.0b1-mk2k.zip (which you should already have)

**Comment by aaronjsolomon** [comment]
YES!! Works great, thank you! :D
