### ISSUE TITLE
Per platform parameters

### ISSUE THREAD

**Issue by Cyorter** [theMK2k/MetropolisLauncher#40]
This is a bad idea for people who uses RetroArch, but I still think for the other emulators is a good idea (or maybe not).

An good alternative would be implement this only for MAME/MESS, but let's remember MAME is updating every month ending and has a HUGE platforms list. So it's possible to list something like the auto configuration Metropolis already has, but exclusively for every working (and probably partially working) platform MAME supports, so doesn't list "NOT WORKING" platforms like Virtual Boy or PC-FX.
Depending of how hard you made the auto configuration for some of emulator, I may help you creating a MAME/MESS auto configuration for every working platform, but first we need to have a verdict and think on how it will work, to avoid problems.

- **Intellivision**: intv -cart "%romfullpath%"
- **PC-FX**: pcfx -cdrom "%romfullpath%"
- **Famicom Twin**: fctwin -cart "%romfullpath%"; fctwin -flop "%romfullpath%"
- **Master System**: sms1 -card "%romfullpath%"; sms1 -cart "%romfullpath%"
- **SC-3000**: sc3000 -cart "%romfullpath%"; sc3000 -cass "%romfullpath%"

If someone has an alternative idea (even if its better or worst than mine) about this I would like to read it because I'm not sure if my idea would really help improving the Launcher.

**Comment by theMK2k** [comment]
This is already covered by 
- adding the same emulator multiple times
- checking a different platform for each
- providing the appropriate command line for each
