### ISSUE TITLE
Kodi .nfo Metadata Export

### ISSUE THREAD

**Issue by KrivenRaven** [theMK2k/MetropolisLauncher#45]
Hey, I brought this up earlier on Reddit. If you do implement some kind of export function for other front ends, like I said I would really like one which would export a .nfo file formatted like the movie .nfo files that Kodi uses. I've already gone to the trouble of doing this for a number of games for my own use, but an automated solution would save me years of work. I know plenty of other people who would like to use Kodi as a gaming front end (or who would like for gaming front ends to incorporate other media. Either way, the community is pretty hungry for a solid all-in-one approach to things). I've already gone to the trouble of figuring out suitable replacements for the majority of video game metadata as far as the .nfo files go just by virtue of having been doing it on my own for so long. If you'd like for me to shoot you some examples let me know, and of course I can always type up more detailed ideas if you would prefer that.

**Comment by theMK2k** [comment]
Hi @KrivenRaven,

thanks for your suggestion.

At first I'd like to get an idea on how a game collection managed by Kodi may look like. Can you tell me if this is a feature of a more recent version and if there is a small tutorial to set things up?

My own Kodi instance is v17.6 and it doesn't seem to support (emulated) games, just Videos, Music and Pictures. What am I missing here?

**Comment by KrivenRaven** [comment]
Kodi 18 actually has RetroPlayer, which is a modified RetroArch built into the Kodi environment. Unfortunately, it doesn't feature metadata at the current time.

What I'm talking about--and what my set-up currently is--looks like the attached images. Those are Kodi 17.6
![kodi games 1](https://user-images.githubusercontent.com/43152557/45390606-d4fc9600-b5ed-11e8-8dfb-b6e1e5e90550.png)
![kodi games 2](https://user-images.githubusercontent.com/43152557/45390607-d4fc9600-b5ed-11e8-9752-4db7decba4c1.png)

Kodi _thinks_ they're movie files. I keep them separated from my movies (and other collections) via tags and a customized home menu. Really easy stuff. You can run PC games, Steam, anything you want, really. ROMs are actually the easiest. In the Advancedsettings.xml file, all you have to do is define .gba, for example, as a movie file extension and associate your emulator as an external player in the playercorefactory file. Instant game library in Kodi, as long as you have .nfo files to pull from. I think more people would definitely adopt this method if there was a program which would generate the .nfo files for them.
