### ISSUE TITLE
Issue on Mass Import

### ISSUE THREAD

**Issue by alandillon** [theMK2k/MetropolisLauncher#46]
When importing a folder I get the following:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

---- Exception Text ----
System.NullReferenceException: Object reference not set to an instance of an object.
   at Metropolis_Launcher.frm_Tag_Parser_Edit.Extract_Content_From_FileName(String FileName, Dictionary`2& dict_Contents, ArrayList& al_Allowed_Extensions)
   at Metropolis_Launcher.frm_Tag_Parser_Edit.Extract_Content_From_FileInfo(FileInfo fi, Dictionary`2& dict_Contents)
   at Metropolis_Launcher.frm_Tag_Parser_Edit.Extract_Content_From_Path(String Path)
   at Metropolis_Launcher.frm_Tag_Parser_Edit.frm_Tag_Parser_Edit_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at DevExpress.XtraEditors.XtraForm.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

---- Loaded Assemblies ----
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Metropolis_Launcher
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/Metropolis_Launcher.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
MKNetDXLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/MKNetDXLib.DLL
----------------------------------------
DevExpress.Utils.v15.2
    Assembly Version: 15.2.17.0
    Win32 Version: 15.2.17.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/DevExpress.Utils.v15.2.DLL
----------------------------------------
DevExpress.Data.v15.2
    Assembly Version: 15.2.17.0
    Win32 Version: 15.2.17.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/DevExpress.Data.v15.2.DLL
----------------------------------------
DevExpress.XtraBars.v15.2
    Assembly Version: 15.2.17.0
    Win32 Version: 15.2.17.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/DevExpress.XtraBars.v15.2.DLL
----------------------------------------
AlphaFS
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/AlphaFS.DLL
----------------------------------------
MKNetLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/MKNetLib.DLL
----------------------------------------
DevExpress.BonusSkins.v15.2
    Assembly Version: 15.2.17.0
    Win32 Version: 15.2.17.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/DevExpress.BonusSkins.v15.2.DLL
----------------------------------------
DevExpress.XtraGrid.v15.2
    Assembly Version: 15.2.17.0
    Win32 Version: 15.2.17.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/DevExpress.XtraGrid.v15.2.DLL
----------------------------------------
DevExpress.XtraEditors.v15.2
    Assembly Version: 15.2.17.0
    Win32 Version: 15.2.17.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/DevExpress.XtraEditors.v15.2.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
DevExpress.Images.v15.2
    Assembly Version: 15.2.17.0
    Win32 Version: 15.2.17.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/DevExpress.Images.v15.2.DLL
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.66.0
    Win32 Version: 1.0.66.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/System.Data.SQLite.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.Data.DataSetExtensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.DataSetExtensions/v4.0_4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll
----------------------------------------
DevExpress.Printing.v15.2.Core
    Assembly Version: 15.2.17.0
    Win32 Version: 15.2.17.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/DevExpress.Printing.v15.2.Core.DLL
----------------------------------------
DevExpress.XtraRichEdit.v15.2
    Assembly Version: 15.2.17.0
    Win32 Version: 15.2.17.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/DevExpress.XtraRichEdit.v15.2.DLL
----------------------------------------
DevExpress.RichEdit.v15.2.Core
    Assembly Version: 15.2.17.0
    Win32 Version: 15.2.17.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/DevExpress.RichEdit.v15.2.Core.DLL
----------------------------------------
DevExpress.XtraGauges.v15.2.Win
    Assembly Version: 15.2.17.0
    Win32 Version: 15.2.17.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/DevExpress.XtraGauges.v15.2.Win.DLL
----------------------------------------
DevExpress.XtraGauges.v15.2.Core
    Assembly Version: 15.2.17.0
    Win32 Version: 15.2.17.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/DevExpress.XtraGauges.v15.2.Core.DLL
----------------------------------------
DevExpress.XtraPivotGrid.v15.2
    Assembly Version: 15.2.17.0
    Win32 Version: 15.2.17.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/DevExpress.XtraPivotGrid.v15.2.DLL
----------------------------------------
DevExpress.PivotGrid.v15.2.Core
    Assembly Version: 15.2.17.0
    Win32 Version: 15.2.17.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/DevExpress.PivotGrid.v15.2.Core.DLL
----------------------------------------
DevExpress.Office.v15.2.Core
    Assembly Version: 15.2.17.0
    Win32 Version: 15.2.17.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/DevExpress.Office.v15.2.Core.DLL
----------------------------------------
DevExpress.XtraTreeList.v15.2
    Assembly Version: 15.2.17.0
    Win32 Version: 15.2.17.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/DevExpress.XtraTreeList.v15.2.DLL
----------------------------------------
SgmlReaderDll
    Assembly Version: 1.8.7.40394
    Win32 Version: 1.8.7.*
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/SgmlReaderDll.DLL
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
UIAutomationClient
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationClient/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationClient.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Ookii.Dialogs
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/Ookii.Dialogs.DLL
----------------------------------------
System.Data.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Linq.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
DevExpress.Data.v15.2.Dynamic_70a2502f-f03a-4293-a981-c54b5d21d9f7
    Assembly Version: 0.0.0.0
    Win32 Version: 15.2.17.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/DevExpress.Data.v15.2.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
SharpCompress.3.5
    Assembly Version: 0.8.2.0
    Win32 Version: 0.8.2.0
    CodeBase: file:///D:/_Games/Metropolis_Launcher/dll/SharpCompress.3.5.DLL
----------------------------------------

**Comment by theMK2k** [comment]
Hi,

thanks for the report. We may need a bit more insight here though.

The error comes from the Tag Parser (see: https://documentation.metropolis-launcher.net/tag_parser_settings.htm?zoom_highlightsub=tag%2Bparser)

So, at the moment I suspect that you have one or more file names where the tag parser trips up.

Now, I don't know how many files you have in the folder, but could you please try to not add the whole folder but chunks of files via the "Add Games (Files)..." menu item until you face the error? Maybe we can find out which file name results in the error and fix the code :)

**Comment by theMK2k** [comment]
Sorry, I can't help without additional information, issue closed for now. Re-open if you find the time to provide help in analysis of the problem.
