### ISSUE TITLE
Much too slow.

### ISSUE THREAD

**Issue by VirgileVILE** [theMK2k/MetropolisLauncher#47]
This is not really an issue, but a relevant problem for me: metropolis launcher is really slow, way too slow. I have timed 30 seconds between the moment I click on the button "games" and the appearance of these. If you compare with a less pretty frontend such as "emulators organizer" where there is no loading time, I chose the fastest of two ... I don't know anyone who likes to wait, you lose a lot of potential users in my opinion.

**Comment by theMK2k** [comment]
Hi @VirgileVILE,

thanks for your comment. Yeah, ML is not to be described as light-weight. And I'm happy that only people who recognize the advantages of its features do actually use it.

Yes, ML has a longer startup time. Yes ML is bloated with features.

If it's not for you, have fun with emulators organizer :)

**Comment by VirgileVILE** [comment]
Currently, to be honest I still use the two softwares because you have done great work with Metropolis, it is undeniable. Thank you for your reply.
(Maybe if it is possible in the future for users to create their own skins, it'll be definitely aesthetically more interesting than other software, even if it is much slower ...)

**Comment by theMK2k** [comment]
Thanks for clearing it up :)

Now I'm curious. Which are the top features in ML that keep you using it?

**Comment by VirgileVILE** [comment]
I really like the retroachievements tab! But it's especially the fact that the interface is both sober and classy that I liked from the start, which is not the case of many software.

**Comment by theMK2k** [comment]
Thanks, the RetroAchievements Tab is one of the latest features. Good to hear it's useful :)

I'll close this issue for now, if there is ever any big bump in startup performance, I'll let you know.
